services:
  - type: web
    name: zoom-bot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gthread -w 1 --threads 4 app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
